// examples/solid/a11y-devtools/src/index.tsx
import { render } from 'solid-js/web'

// devtool imports
import { TanStackDevtools } from '@tanstack/solid-devtools'
import { a11yDevtoolsPlugin } from '@tanstack/devtools-a11y/solid'

import App from './app'

function Root() {
  return (
    <>
      <App />

      <TanStackDevtools plugins={[a11yDevtoolsPlugin()]} />
    </>
  )
}

render(() => <Root />, document.getElementById('root')!)

// examples/react/custom-devtools/src/index.tsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { TanstackDevtools } from '@tanstack/react-devtools'

import App from './App'
import CustomDevtoolPanel from './CustomDevtoolsPanel'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />

    <TanstackDevtools
      plugins={[
        {
          name: 'Custom devtools',
          render: <CustomDevtoolPanel />,
        },
      ]}
    />
  </StrictMode>,
)
