// examples/solid/a11y-devtools/src/index.tsx
import { render } from 'solid-js/web'

// devtool imports
import { TanStackDevtools } from '@tanstack/solid-devtools'
import { a11yDevtoolsPlugin } from '@tanstack/devtools-a11y/solid'

import App from './app'

function Root() {
  return (
    <>
      <App />

      <TanStackDevtools plugins={[a11yDevtoolsPlugin()]} />
    </>
  )
}

render(() => <Root />, document.getElementById('root')!)

// examples/react/a11y-devtools/src/index.tsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { TanStackDevtools } from '@tanstack/react-devtools'
import { a11yDevtoolsPlugin } from '@tanstack/devtools-a11y/react'

import App from './App'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
    <TanStackDevtools plugins={[a11yDevtoolsPlugin()]} />
  </StrictMode>,
)
