// examples/react/basic/src/index.tsx
import ReactDOM from 'react-dom/client'
import { Devtools } from '@tanstack/react-devtools'
function App() {
  return (
    <div>
      <h1>TanStack Devtools Basic Example</h1>
      <Devtools options={{
        openHotkey: ["Shift", "B"]
      }} />
    </div>
  )
}

const root = ReactDOM.createRoot(document.getElementById('root')!)
root.render(<App />)

// examples/solid/basic/src/index.tsx
import { render } from 'solid-js/web'
import { Devtools } from '@tanstack/solid-devtools'
function App() {
  return (
    <div>
      <h1>TanStack Devtools Basic Example</h1>
      <Devtools options={{
        openHotkey: ["Shift", "B"]
      }} />
    </div>
  )
}

render(() => <App />, document.getElementById('root')!)
